@contentType = application/json
@host = http://localhost:8080/v1
@accessToken = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImI4OWRlZWI1LTlhOTgtNDk2Zi1iYTQ3LWZjYzkyZDU3NmU0YyJ9.eyJpZCI6IjYyNzc0MjI2YTA2MTY1YjU5Njk2NGU5NiIsInVzZXJuYW1lIjoia2V2aW53b25nIiwiaWF0IjoxNjUyMDc2NzAxLCJleHAiOjMzMDQyMzk4MDIsImlzcyI6InBvaW50cG9pbnQifQ.aAFIoRsh6Flt2vstacCqwC6OA4A8f3-J_4pHwRMeHfORLXVLCewbwyHnvSxOqI1TimOW0jrUwZMvhwIMjh3m5q89n5f9-tWv46hLKY5J_hntQmd-t8fnImhV2mw4hDgSs6HzvtbRIJoe4hxj8cD3WptnrDREafkeDC9rJLWhUrpYX5fXn8X1jtjWzOt0gcryFXov6zTJw1vn_vCIpqGVrSYIU-yQ21IZDBOyQgXi_Rx9owNn3uthpxkE66o4bGQnKfaP25ySaaj-C9HQOCNdxKHnUfUYq8SxRWE18SA0pfasn7P5b5t9MfOLi_OeIiPR9km8jWW9nknNDcxTHCHl7w

###
GET {{host}}/.well-known/jwks.json

###
GET {{host}}/users/search
    ?text=kevinwong
Authorization: {{accessToken}}